### ISSUE TITLE
Tooltips fail to hide after a zoom event

### ISSUE THREAD

**Issue by vincemtnz** [IvanCoronado/running-statistics-from-Barcelona#5]
To reproduce: click on a marker (tooltip shows and the marker is set to `active`), zoom in or out, click on a different marker. 

Basically, all markers loose their active state once you zoom so `hideAllTooltips()` fails. This: https://github.com/IvanCoronado/running-statistics-from-Barcelona/blob/0a86c48fda969dfb33694b89c6199cbb981ed86b/src/app/main/main.controller.js#L300 returns an empty array.

Nice job by the way :+1:

**Comment by IvanCoronado** [comment]
Thanks @eyko :+1:
